
/* 	PM2 monitoring
	
	pm2 list		lista all running index.js clusters
	pm2 show [id]	give more details for specific cluster
	pm2 monit 		display current system usage by all node clusters
	pm2 logs		show the logs generated by index.js
*/

var pm2 = require('pm2');

pm2.connect(function() {
  pm2.start({
  	// index.js can also be started on its own
    script    : 'index.js',    
    // allows index.js to run as a cluster      
    exec_mode : 'cluster',
    // total number of clusters 	
    instances : 2,
    // the server will restart itself if it reaches 200mb                
    max_memory_restart : '200M'   
  }, function(err, apps) {
    pm2.disconnect();
  });
});